---
title: "Tarifas de importação dos EUA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(flexdashboard)
library(tidyverse)
library(sf)
library(spData)
library(colorspace)
library(plotly)
library(DT)
#library(ggiraph)

data("world")

tarifas_trump <- read_csv("tarifas_trump.csv")


comercio_exterior <- readRDS("comercio_exterior.rds")

cor_mar<- "#008080" #57A8C2

saldo_comercio_eua<- 
  (comercio_exterior %>%
  filter(reporter_iso == "USA"))$saldo

comercio_mundial<-
  sum(comercio_exterior$export[comercio_exterior$partner_desc=="World"])

sum(comercio_exterior$import[comercio_exterior$partner_desc=="World"])




```

# Mapa de novas tarifas

### Mapa

```{r dpi=300}
# renderGirafe({
#   
#   dado_texto<- tibble(x=-160, y=-50, text = "Elaboração: Fernando Barbalho")  
#     
# map<-  
# world %>%
#   st_make_valid() %>% 
#   st_simplify(dTolerance = 0.01) %>% 
#   left_join(
#     tarifas_trump %>%
#       rename(tarifa = new_us_tariff)
#   ) %>%
#   ggplot() +
#   geom_sf_interactive(aes(fill = tarifa, tooltip = paste(name_long, ifelse(is.na(tarifa),"",": ") , ifelse(is.na(tarifa),"",tarifa) , ifelse(is.na(tarifa),"","%")))) +
#   scale_fill_continuous_sequential(palette = "Heat 2")+
#     theme_void() +
#     theme(
#       panel.background = element_rect(fill=cor_mar),
#       text = element_text(colour = "black", size=45),
#       legend.key.height = unit(3, "cm"),  # Key heigh,
#       legend.key.width = unit(2, "cm"),  # Key heigh,
#       plot.title = element_text(
#       hjust = 0.5,
#       size = 75,
#       color = "darkblue",
#       face = "bold")
#       
#     ) +
#    coord_sf(xlim = c(-180,180), ylim=c(-50,82))+
#    #geom_text(data = dado_texto, aes(x=x, y=y, label= text) , color = "white") +
#    labs(
#       title = "Novas tarifas dos EUA para importação",
#       caption = "Fonte: The Guardian. Elaboração: Fernando Barbalho",
#       fill= "%"
#     )
# 
# 
#   #ggplotly(map, tooltip = c("text")) 
# 
#   return(girafe(code = print(map), 
#                   width_svg = (60),
#                   height_svg = (24)))
# 
#   # girafe(ggobj = map,
#   # options = list(opts_sizing(rescale = FALSE ),
#   #                ))
#   
# })

renderPlotly({

dado_texto<- tibble(x=-160, y=-50, text = "Elaboração: Fernando Barbalho")

map<-
world %>%
  st_make_valid() %>%
  st_simplify(dTolerance = 0.01) %>%
  left_join(
    tarifas_trump %>%
      rename(tarifa = new_us_tariff)
  ) %>%
  ggplot() +
  geom_sf(aes(fill = tarifa, text = paste(name_long, ifelse(is.na(tarifa),"",": ") , ifelse(is.na(tarifa),"",tarifa) , ifelse(is.na(tarifa),"","%")))) +
  scale_fill_continuous_sequential(palette = "Heat 2")+
    theme_void() +
    theme(
      panel.background = element_rect(fill=cor_mar),
      text = element_text(colour = "black"),

    ) +
   coord_sf(xlim = c(-180,180), ylim=c(-50,82))+
   geom_text(data = dado_texto, aes(x=x, y=y, label= text) , color = "white") +
   labs(
      title = "Novas tarifas dos EUA para importação",
      caption = "Fonte: Guardian.",
      fill= "%"
    )


  ggplotly(map, tooltip = c("text"))
})




```

# Mapa de tarifas alegadamente aplicadas aos EUA

## Column

### Mapa

```{r dpi=300}
renderPlotly({

dado_texto<- tibble(x=-160, y=-50, text = "Elaboração: Fernando Barbalho")   
    
map<-  
world %>%
  left_join(
    tarifas_trump %>%
      rename(tarifa = alleged_tariff_charged_to_us)
  ) %>%
  ggplot() +
  geom_sf(aes(fill = tarifa, text = paste(name_long, ifelse(is.na(tarifa),"",": ") , ifelse(is.na(tarifa),"",tarifa) , ifelse(is.na(tarifa),"","%")))) +
  scale_fill_continuous_sequential(palette = "Heat 2")+
    theme_void() +
    theme(
      panel.background = element_rect(fill=cor_mar),
      text = element_text(colour = "black"),

    ) +
    coord_sf(xlim = c(-180,180), ylim=c(-50,82))+
  geom_text(data = dado_texto, aes(x=x, y=y, label= text) , color = "white") +
    labs(
      title = "Tarifas impostas aos EUA (conforme alegado pelo governo dos EUA)",
      caption = "Fonte: Guardian.",
      fill= "%"
    )


  ggplotly(map, tooltip = c("text"))
})




```

# Mapa do comércio exterior (comércio com EUA)

## Column

### Mapa

```{r dpi=300}
renderPlotly({
  
dado_texto<- tibble(x=-140, y=-50, text = "Fonte: UN Comtrade (2023). Elaboração: Fernando Barbalho") 
  
  dados_mapa<-  
    world %>%
    left_join(
      comercio_exterior %>%
        filter(partner_desc == "USA") %>%
        rename(iso_a3 = reporter_iso) %>%
        mutate(saldo_comercial_rel_pais = (round(saldo/saldo_comercio_eua,5)*-1)*100) %>%
        inner_join(
          tarifas_trump %>%
            select(iso_a3, iso_a2)
        )
    ) 
  
  fab<-
    dados_mapa %>%
    filter(iso_a2=="PY") %>%
    select(name_long, saldo_comercial_rel_pais )

  print(fab)

  fab<-
  cut(dados_mapa$saldo_comercial_rel_pais,
                           breaks = c(-11, seq(-10, 25, by = 0.2), 30))
  
  map<-
    
    dados_mapa %>%
    ggplot() +
    geom_sf(aes(fill = cut(saldo_comercial_rel_pais,
                           breaks = c(-11, -10,-3, -1,-0.001,0,0.001, 1,3, 10,30)),
                text = paste(name_long, ifelse(is.na(saldo_comercial_rel_pais),"",": ") , ifelse(is.na(saldo_comercial_rel_pais),"",saldo_comercial_rel_pais) , ifelse(is.na(saldo_comercial_rel_pais),"","%")))) +
    scale_fill_discrete_divergingx(palette = "Rdbu",
                                   na.value = "gray50") +
    theme_void() +
    theme(
      panel.background = element_rect(fill = cor_mar),
      text = element_text(colour = "black")
    )  +
    coord_sf(xlim = c(-180,180), ylim=c(-50,82))+
  #geom_text(x=-140,y =-50,aes( label = "Fonte: UN Comtrade (2023). Elaboração: Fernando Barbalho"))+
    geom_text(data = dado_texto, aes(x=x, y=y, label= text) , color = "white") +
    labs(
      title = "Saldo comercial dos EUA: proporção por país parceiro",
      caption = "Fonte: Guardian.",
      fill= "%"
    )
  
  
  ggplotly(map, tooltip = c("text"))
})




```

# Mapa do comércio exterior (exportações mundo)

## Column

### Mapa 

```{r dpi=300}
renderPlotly({
  
  dado_texto<- tibble(x=-140, y=-50, text = "Fonte: UN Comtrade (2023). Elaboração: Fernando Barbalho") 
  
  dados_mapa<-  
    world %>%
    left_join(
      comercio_exterior %>%
        filter(partner_desc == "World") %>%
        rename(iso_a3 = reporter_iso) %>%
        mutate(participao_exportacao_mundial = (round(export/comercio_mundial,5))*100) %>%
        inner_join(
          tarifas_trump %>%
            select(iso_a3, iso_a2)
        )
    ) 
  
  fab<-
    dados_mapa %>%
    filter(iso_a2=="PY") %>%
    select(name_long, participao_exportacao_mundial )

  print(fab)
  
  map<-
    
   dados_mapa %>%
    ggplot() +
    geom_sf(aes(fill = cut(participao_exportacao_mundial,
                           breaks = c(-11, seq(-10, 25, by = 0.2), 30)),
                text = paste(name_long, ifelse(is.na(participao_exportacao_mundial),"",": ") , ifelse(is.na(participao_exportacao_mundial),"",participao_exportacao_mundial) , ifelse(is.na(participao_exportacao_mundial),"","%")))) +
    scale_fill_discrete_sequential (palette = "Heat 2",
                                   na.value = "gray50") +
    theme_void() +
    theme(
      panel.background = element_rect(fill = cor_mar),
      text = element_text(colour = "black")
    )  +
    coord_sf(xlim = c(-180,180), ylim=c(-50,82))+
  #geom_text(x=-140,y =-50, aes(label = "Fonte: UN Comtrade (2023). Elaboração: Fernando Barbalho"))+
    geom_text(data = dado_texto, aes(x=x, y=y, label= text) , color = "white") +
    labs(
      title = "Participação das exportações no comércio mundial ",
      caption = "Fonte: Guardian.",
      fill= "%"
    ) 
  
  ggplotly(map, tooltip = c("text"))
})




```

# Mapa do comércio exterior (importações mundo)

## Column

### Mapa

```{r dpi=300}
renderPlotly({
  
  dado_texto<- tibble(x=-140, y=-50, text = "Fonte: UN Comtrade (2023). Elaboração: Fernando Barbalho") 
  
  dados_mapa<-  
    world %>%
    left_join(
      comercio_exterior %>%
        filter(partner_desc == "World") %>%
        rename(iso_a3 = reporter_iso) %>%
        mutate(participao_importacao_mundial = (round(import/comercio_mundial,5))*100) %>%
        inner_join(
          tarifas_trump %>%
            select(iso_a3, iso_a2)
        )
    ) 
  
  
  
  map<-
    
   dados_mapa %>%
    ggplot() +
    geom_sf(aes(fill = cut(participao_importacao_mundial,
                           #breaks = c(-Inf, -100, seq(-90, 90, by = 10), 100, Inf)),
                           breaks = c(-11, seq(-10, 25, by = 0.2), 30)),
                text = paste(name_long, ifelse(is.na(participao_importacao_mundial),"",": ") , ifelse(is.na(participao_importacao_mundial),"",participao_importacao_mundial) , ifelse(is.na(participao_importacao_mundial),"","%")))) +
    scale_fill_discrete_sequential (palette = "Heat 2",
                                   na.value = "gray50") +
    theme_void() +
    theme(
      panel.background = element_rect(fill = cor_mar),
      text = element_text(colour = "black")
    )  +
    coord_sf(xlim = c(-180,180), ylim=c(-50,82))+
  #geom_text(x=-140,y =-50, aes(label = "Fonte: UN Comtrade (2023). Elaboração: Fernando Barbalho"))+
    geom_text(data = dado_texto, aes(x=x, y=y, label= text) , color = "white") +
    labs(
      title = "Participação das importações no comércio mundial ",
      caption = "Fonte: Guardian.",
      fill= "%"
    ) 
  
  ggplotly(map, tooltip = c("text"))
})




```

# Tabela completa

## Column

### Tabela

```{r}

renderDT({
  

  tabela<-
    as_tibble( world %>%
    left_join(
      comercio_exterior %>%
        rename(iso_a3 = reporter_iso) %>%
        mutate(saldo_comercial_rel_pais = (round(saldo/saldo_comercio_eua,5)*-1)*100,
               participao_exportacao_mundial = (round(export/comercio_mundial,5))*100,
               participao_importacao_mundial = (round(import/comercio_mundial,5))*100
               ) %>%
        inner_join(
          tarifas_trump %>%
            select(iso_a3, iso_a2, new_us_tariff, alleged_tariff_charged_to_us)
        )
    ) ) %>%
    filter(!is.na(partner_desc)) %>%
    mutate(name_long = as.factor(name_long),
           iso_a2 =as.factor(iso_a2),
           iso_a3 = as.factor(iso_a3),
           continent = as.factor(continent),
           subregion = as.factor(subregion)) %>%
    select(name_long, iso_a2, iso_a3, continent, subregion, new_us_tariff, alleged_tariff_charged_to_us, partner_desc, import, export, saldo, saldo_comercial_rel_pais,participao_exportacao_mundial, participao_importacao_mundial ) %>%
    pivot_wider(names_from = partner_desc,
                values_from = c( import, export,saldo,  saldo_comercial_rel_pais,participao_exportacao_mundial, participao_importacao_mundial)) %>%
    select(-c(saldo_comercial_rel_pais_World,participao_exportacao_mundial_USA, participao_importacao_mundial_USA))
  
  
  

  nomes_colunas<- c("País", "Código ISO-2", "Código ISO-3", "Continente", "Sub-região", "Nova Tarifa (%)", "Tarifa alegada (%)","Importação Mundo (US$)", "Importação EUA (US$)","Exportação mundo (US$)","Exportação EUA (US$)", "Saldo Mundo (US$)", "Saldo EUA (US$)", "Participação saldo EUA (%)", "Participação exportação mundial (%)", "Participação importação mundial (%)")
  

  
  tabela %>%
    arrange(name_long, desc(new_us_tariff)) %>%
    DT::datatable(
      filter = "top",
      rownames = FALSE,
      colnames = nomes_colunas,
      fillContainer = TRUE,
      selection = c("none"),
      extensions = 'Buttons',
      options = list(
        columnDefs = list(list(className = 'dt-right', targets = 6:15)),
        ordering=TRUE,
        paging=TRUE,
        searching= TRUE,
        info = TRUE,
        pageLength = NROW(tabela),
        dom = 'Bfrtip',
        buttons = c('copy',"csv","excel")
      ))%>%
    formatRound(6:13,digits = 2, mark=".", dec.mark= ",")%>%
    formatRound(14:16,digits = 3, mark=".", dec.mark= ",")
  
  
})

  
```
